// layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Anton } from "next/font/google";

// 1. Definisikan font Anton
const fontHeading = Anton({
  subsets: ["latin"],
  weight: "400",
  // PENTING: Set variabel CSS kustom untuk digunakan di Tailwind
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Firaz Fulvian Hafiz | Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 2. Hanya tambahkan variabel font ke <body> atau <html>. */}
      {/* Jangan menggunakan anton.className agar tidak menimpa font default. */}
      <body className={`${fontHeading.variable} antialiased`}>{children}</body>
    </html>
  );
}
