// layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Anton, Poppins } from "next/font/google";

// 1. Definisikan font Anton
const fontHeading = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

const fontBody = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Firaz Fulvian Hafiz | Personal Portfolio",
  description: "Generated by create next app",
  // ✨ PERBAIKAN: Tambahkan properti icons
  icons: {
    icon: "/icon.svg", // Next.js akan mencari file ini di folder 'app' (root)
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontHeading.variable} ${fontBody.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
